import { 
    SportsEsportsOutlined,
    SportsEsports,
    SportsBaseball,
    SportsBaseballOutlined,
    Business,
    Tv,
    Star,
    StarOutline,
    Pets,
    Face3,
    Face3Outlined,
    ColorLens,
    ColorLensOutlined,
    DirectionsCar,
    DirectionsCarOutlined,
    AutoAwesome,
    AutoAwesomeOutlined,
    Diversity3,
    AccountBalance,
    AccountBalanceOutlined,
    Checkroom,
    Restaurant,
    AutoStories,
    AutoStoriesOutlined,
    Skateboarding,
    Gavel,
    School,
    SchoolOutlined,
    TheatersOutlined,
    LibraryMusic,
    LibraryMusicOutlined,
    Place,
    PlaceOutlined,
    SettingsInputAntenna,
    HowToVote,
    HowToVoteOutlined,
    Terminal,
    LocalLibrary,
    LocalLibraryOutlined,
    Church,
    ChurchOutlined,
    Science,
    ScienceOutlined,
    Smartphone,
} from "@mui/icons-material";

import { SvgIconTypeMap } from "@mui/material";
import { OverridableComponent } from "@mui/material/OverridableComponent";

export interface TopicIcon {
    title: string;
    path: string;
    icon: OverridableComponent<SvgIconTypeMap<{}, "svg">> & {muiName: string;};
    iconPath?: OverridableComponent<SvgIconTypeMap<{}, "svg">> & {muiName: string;};
}

export const topicIcons = <TopicIcon[]>[
    {title: 'Video games', path: '/videogames', icon: SportsEsportsOutlined, iconPath: SportsEsports},
    {title: 'Sports', path: '/sports', icon: SportsBaseballOutlined, iconPath: SportsBaseball},
    {title: 'Business', path: '/business', icon: Business},
    {title: 'TV', path: '/tv', icon: Tv},
    {title: 'Famous', path: '/famous', icon: StarOutline, iconPath: Star},
    {title: 'Animals / Pets', path: '/animals-pets', icon: Pets},
    {title: 'Anime / Animation', path: '/anime-animation', icon: Face3Outlined, iconPath: Face3},
    {title: 'Art', path: '/art', icon: ColorLensOutlined, iconPath: ColorLens},
    {title: 'Cars / Motors / Vehicles', path: '/vehicles', icon: DirectionsCarOutlined, iconPath: DirectionsCar},
    {title: 'Crafts', path: '/crafts', icon: AutoAwesomeOutlined, iconPath: AutoAwesome},
    {title: 'Culture / Races / Ethnicities', path: '/culture', icon: Diversity3},
    {title: 'Ethics / Philosophy', path: '/ethics-philosophy', icon: AccountBalanceOutlined, iconPath: AccountBalance},
    {title: 'Fashion', path: '/fashion', icon: Checkroom},
    {title: 'Meals / Drinks', path: '/meals-drinks', icon: Restaurant},
    {title: 'History', path: '/history', icon: AutoStoriesOutlined, iconPath: AutoStories},
    {title: 'Hobbies', path: '/hobbies', icon: Skateboarding},
    {title: 'Law', path: '/law', icon: Gavel},
    {title: 'Learning / Education', path: '/education', icon: SchoolOutlined, iconPath: School},
    {title: 'Movies', path: '/movies', icon: TheatersOutlined},
    {title: 'Music', path: '/music', icon: LibraryMusicOutlined, iconPath: LibraryMusic},
    {title: 'Places', path: '/places', icon: PlaceOutlined, iconPath: Place},
    {title: 'Podcast / Streaming', path: '/podcast-streaming', icon: SettingsInputAntenna},
    {title: 'Politics', path: '/politics', icon: HowToVoteOutlined, iconPath: HowToVote},
    {title: 'Programming', path: '/programming', icon: Terminal},
    {title: 'Literature', path: '/literature', icon: LocalLibraryOutlined, iconPath: LocalLibrary},
    {title: 'Religion / Spirituality', path: '/religion-spirituality', icon: ChurchOutlined, iconPath: Church},
    {title: 'Science', path: '/science', icon: ScienceOutlined, iconPath: Science},
    {title: 'Technology', path: '/tech', icon: Smartphone},
]
